def get_locals_txt():
    names = """LOCALDAY LOCALDAY2 LOCALDAYNAME LOCALDOW LOCALMONTH
LOCALMONTHABBREV LOCALMONTHNAME LOCALTIME LOCALYEAR LOCALTIMESTAMP
NUMBEROFARTICLES NUMBEROFPAGES NUMBEROFFILES NUMBEROFUSERS CURRENTVERSION
"""
    names = [x for x in names.split() if x]

    return "\n---\n".join(["%s={{%s}}" % (x, x) for x in names])


    
