#! /usr/bin/env python

# please install this file as pre-commit hook with the following command:
#
#    ln -sf ../../make-manifest .git/hooks/pre-commit
#

import os


def main():
    files = sorted(set([x.strip() for x in os.popen("git ls-files")] + ["mwlib/_uscan.cc"])
                   - set(("make-manifest", "Makefile", ".gitignore", "make-release")))
    f = open("MANIFEST.in", "w")
    for x in files:
        f.write("include %s\n" % x)
    f.close()
    os.system("git add MANIFEST.in; git diff --cached MANIFEST.in | cat")

if __name__ == '__main__':
    main()
