DEPRECATED_ALBUM_INFOBOX_PARAMS = [
    "empty weight main",
    "height main",
    "area main",
    "ceiling main",
    "stall speed main",
    "max speed main",
    "range main",
    "cruise speed main",
    "loaded weight main",
    "climb rate main",
    "length main",
    "span main",
    "power main",
    "max takeoff weight main",
    "empty weight alt",
    "height alt",
    "area alt",
    "ceiling alt",
    "stall speed alt",
    "max speed alt",
    "range alt",
    "cruise speed alt",
    "loaded weight alt",
    "length alt",
    "climb rate alt",
    "span alt",
    "power alt",
    "engine (prop)",
    "plane or copter?",
    "jet or prop?",
    "max takeoff weight alt",
    "number of props",
    "type of prop",
    "power/mass alt",
    "power/mass main",
    "loading main",
    "loading alt",
]
